apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-test
  labels:
    run: test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: run
                operator: In
                values:
                  - carpenter
  containers:
    - name: test
      image: bhabanisn/color-frontend
      resources: {}
      readinessProbe:
        httpGet:
          port: 8082
          path: /color/ready
        initialDelaySeconds: 15
        periodSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
  