apiVersion: v1
kind: Pod
metadata:
  name: title
  labels:
    role: title
spec:
  containers:
    - name: title
      image: nginx
      command: ["/bin/echo"]
      args: ["CKAD is not deficult"]

      imagePullPolicy: IfNotPresent
      ports:
        - name: title
          containerPort: 80
          protocol: TCP

  restartPolicy: Always
  resources:
    requests:
      cpu: "250m"
      memory: "4064Mi"

  